package algonquin.cst2335_yikaiwang_finalproject.nasaphotos.model;

import androidx.room.ColumnInfo;
import androidx.room.PrimaryKey;

public class NasaPhotoDetails {

    /** The primary key in the database */
    @ColumnInfo(name = "id")
    @PrimaryKey
    private Integer dbId;

    /** Photo id generated by Nasa Mars Photo */
    @ColumnInfo(name = "nasa_photo_id")
    private Integer id;

    /** The width of the photo */
    @ColumnInfo(name = "camera")
    private String camera;

    /** The home page of the photo */
    @ColumnInfo(name = "url")
    private String url;

    /** The name of photo */
    @ColumnInfo(name = "rover")
    private String rover;

    /** The url of the photo's thumbnail */
    @ColumnInfo(name = "thumbnail")
    private transient String thumbnail;

    /** The url of the photo */
    @ColumnInfo(name = "photoUrl")
    private transient String photoUrl;

    public NasaPhotoDetails(String cameraName, String photoUrl) {
        camera = cameraName;
        url = photoUrl;
    }

    public Integer getDbId() {
        return dbId;
    }

    public void setDbId(Integer dbId) {
        this.dbId = dbId;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCamera() {
        return camera;
    }

    public void setCamera(String camera) {
        this.camera = camera;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getRover() {
        return rover;
    }

    public void setRover(String rover) {
        this.rover = rover;
    }

    public String getThumbnail() {
        return thumbnail;
    }

    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    public String getPhotoUrl() {
        return photoUrl;
    }

    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

}
